import Sparkle

/// Thin wrapper around Sparkle's standard updater controller. The feed URL
/// and public EdDSA key live in Info.plist (SUFeedURL / SUPublicEDKey),
/// generated by build-app.sh — see scripts/release.sh for how the appcast
/// itself is published to GitHub Releases.
final class AppUpdater {
    static let shared = AppUpdater()

    let controller = SPUStandardUpdaterController(
        startingUpdater: true,
        updaterDelegate: nil,
        userDriverDelegate: nil
    )

    func checkForUpdates() {
        controller.checkForUpdates(nil)
    }
}
