import Sparkle

/// Thin wrapper around Sparkle's standard updater controller. The feed URL
/// and public EdDSA key live in Info.plist (SUFeedURL / SUPublicEDKey),
/// generated by build-app.sh — see scripts/release.sh for how the appcast
/// itself is published to GitHub Releases.
final class AppUpdater: NSObject, SPUUpdaterDelegate {
    static let shared = AppUpdater()

    // Implicitement optionnelle : Swift l'initialise à nil sans exiger une
    // valeur avant super.init(), ce qui permet de passer `self` (donc de
    // l'avoir déjà construit) comme updaterDelegate juste après — Sparkle ne
    // l'expose que via cet initialiseur, pas comme propriété modifiable.
    var controller: SPUStandardUpdaterController!
    weak var appDelegate: AppDelegate?

    private override init() {
        super.init()
        controller = SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: self,
            userDriverDelegate: nil
        )
    }

    /// Ouvre la fenêtre Sparkle standard (menu "Rechercher les mises à jour…").
    func checkForUpdates() {
        controller.checkForUpdates(nil)
    }

    /// Vérification silencieuse, sans aucune UI — utilisée au lancement de
    /// l'app. Renseigne juste le delegate (didFindValidUpdate) si une mise à
    /// jour existe ; ne télécharge rien.
    func checkSilently() {
        controller.updater.checkForUpdateInformation()
    }

    /// Déclenché par le bouton de la bannière « Mise à jour disponible » côté
    /// web : télécharge et installe directement, sans l'écran de confirmation
    /// standard de Sparkle (voir didFinishUpdateCycleForUpdateCheck ci-dessous
    /// pour la remise à zéro). L'app se ferme et relance automatiquement une
    /// fois l'installation terminée.
    func installPendingUpdate() {
        controller.updater.automaticallyDownloadsUpdates = true
        controller.checkForUpdates(nil)
    }

    // MARK: - SPUUpdaterDelegate

    func updater(_ updater: SPUUpdater, didFindValidUpdate item: SUAppcastItem) {
        appDelegate?.notifyUpdateAvailable(version: item.displayVersionString)
    }

    func updater(_ updater: SPUUpdater, didFinishUpdateCycleFor updateCheck: SPUUpdateCheck, error: Error?) {
        // Revient au comportement par défaut (le clic sur la bannière reste
        // nécessaire) — sinon toute vérification ultérieure télécharge et
        // installe silencieusement, sans jamais repasser par le bouton.
        updater.automaticallyDownloadsUpdates = false
    }
}
